<a href="https://colab.research.google.com/github/diya-nagchaudhury/learn_pytorch/blob/main/reshaping_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [4]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.1224, 0.5887, 0.9796, 0.2960],
         [0.9528, 0.7441, 0.1599, 0.5840],
         [0.3508, 0.4542, 0.6318, 0.2401]],

        [[0.2572, 0.7429, 0.4567, 0.9579],
         [0.5481, 0.4979, 0.8873, 0.8252],
         [0.3100, 0.9322, 0.8838, 0.1947]]])

In [8]:
b.permute(2, 0, 1)

tensor([[[0.1224, 0.9528, 0.3508],
         [0.2572, 0.5481, 0.3100]],

        [[0.5887, 0.7441, 0.4542],
         [0.7429, 0.4979, 0.9322]],

        [[0.9796, 0.1599, 0.6318],
         [0.4567, 0.8873, 0.8838]],

        [[0.2960, 0.5840, 0.2401],
         [0.9579, 0.8252, 0.1947]]])

In [18]:
# squeeze and unsqueeze operations