<a href="https://colab.research.google.com/github/diya-nagchaudhury/learn_pytorch/blob/main/tensor_operations_on_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [6]:
device = torch.device('cuda')
print(device)

cuda


In [8]:
# Creating a new tensor on GPU
a = torch.tensor([1, 2, 3], device = device)
a

tensor([1, 2, 3], device='cuda:0')

In [11]:
# Move an existing tensor to GPU
b = torch.tensor([1, 2, 3.0])
b

tensor([1., 2., 3.])

In [12]:
b.to(device)

tensor([1., 2., 3.], device='cuda:0')

In [13]:
b + 5

tensor([6., 7., 8.])

##### Performing matrix multiplication on CPU vs GPU

In [17]:
import time

size = 1000
m1 = torch.randn(size, size)
m2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(m1, m2)
cpu_time = time.time() - start_time

m3 = m1.to(device)
m4 = m2.to(device)

start_time = time.time()
result_gpu = torch.matmul(m3, m4)
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")
print(f"Time on GPU: {gpu_time:.4f} seconds")

print(f"Speedup: {cpu_time / gpu_time:.2f}x")

Time on CPU: 0.0274 seconds
Time on GPU: 0.0011 seconds
Speedup: 25.62x
